---
all:
  children:
  # --- AWS environment ---
    aws:
      hosts:
        aws_linux:
          aws-server-01: 13.61.1.20
          aws-server-02: 16.16.58.178
          aws-server-03: 51.20.52.147
        vars:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/Totorial.pem


# --- On-Premise Environment ---
# A group for on-premise server, specifically with Docker installed.
# We will use 'localhost' since this is a local server.
on_premise:
  hosts:
    localhost:
      # This variable tells Ansible to connect to the local machine directly.
      ansible_connection: local
